services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80"
    volumes:
      - app_storage:/var/www/html/storage/app
      - app_logs:/var/www/html/storage/logs
    restart: unless-stopped

volumes:
  app_storage:
  app_logs:
